<?php

require_once "../../auth/check_auth.php";
require_once __DIR__ . "/../../includes/report_functions.php";

$id = $_GET['id'] ?? null;
$report = $_SESSION['reports'][$id] ?? null;

if (!$report) {
    header("Location: index.php");
    exit;
}

header('Content-Type: text/plain');
header('Content-Disposition: attachment; filename="' . rawurlencode($report['report_name']) . '.txt"');

echo "Report ID: {$report['report_id']}\n";
echo "Report Name: {$report['report_name']}\n";
echo "Report Type: {$report['report_type']}\n";
echo "Generated By: {$report['generated_by']}\n";
echo "Date Generated: {$report['date_generated']}\n";
echo "Status: {$report['status']}\n";
echo str_repeat("-", 40) . "\n\n";

$type = $report['report_type'];

if ($type === 'Procurement Report') {

    $d = generateProcurementSummary();
    echo "PROCUREMENT SUMMARY\n";
    echo "Total Requests: {$d['total']}\n";
    echo "Pending: {$d['pending']}\n";
    echo "Approved: {$d['approved']}\n";
    echo "Delivered: {$d['delivered']}\n";
    echo "Rejected: {$d['rejected']}\n\n";
    echo "By Supplier:\n";
    foreach ($d['by_supplier'] as $supplier => $count) {
        echo "  {$supplier}: {$count}\n";
    }

} elseif ($type === 'Inventory Report') {

    $d = generateInventorySummary();
    echo "INVENTORY SUMMARY\n";
    echo "Total Items: {$d['total_items']}\n";
    echo "Total Stock: {$d['total_stock']}\n";
    echo "Low Stock Items: {$d['low_stock']}\n";
    echo "Out of Stock Items: {$d['out_of_stock']}\n";
    echo "Ready for Registration: {$d['ready_for_registration']}\n";

} elseif ($type === 'Asset Report') {

    $d = generateAssetSummary();
    echo "ASSET REGISTRY SUMMARY\n";
    echo "Total Assets: {$d['total']}\n";
    echo "Available: {$d['available']}\n";
    echo "Assigned: {$d['assigned']}\n";
    echo "Under Maintenance: {$d['under_maintenance']}\n";
    echo "Lost: {$d['lost']}\n\n";
    echo "By Category:\n";
    foreach ($d['by_category'] as $cat => $count) {
        echo "  {$cat}: {$count}\n";
    }

} elseif ($type === 'Maintenance Report') {

    $d = generateMaintenanceSummary();
    echo "MAINTENANCE SUMMARY\n";
    echo "Total Records: {$d['total']}\n";
    echo "Scheduled: {$d['scheduled']}\n";
    echo "In Progress: {$d['in_progress']}\n";
    echo "Completed: {$d['completed']}\n";

} elseif ($type === 'Audit Report') {

    $d = generateAuditSummary();
    echo "AUDIT SUMMARY\n";
    echo "Total Audits: {$d['total']}\n";
    echo "Completed: {$d['completed']}\n";
    echo "Pending: {$d['pending']}\n";

} elseif ($type === 'Full System Report') {

    $d = generateFullSystemSummary();
    echo "FULL SYSTEM SUMMARY\n\n";
    echo "Procurement — Total: {$d['procurement']['total']}, Pending: {$d['procurement']['pending']}, Approved: {$d['procurement']['approved']}, Delivered: {$d['procurement']['delivered']}, Rejected: {$d['procurement']['rejected']}\n";
    echo "Inventory — Items: {$d['inventory']['total_items']}, Stock: {$d['inventory']['total_stock']}, Low Stock: {$d['inventory']['low_stock']}, Out of Stock: {$d['inventory']['out_of_stock']}\n";
    echo "Assets — Total: {$d['assets']['total']}, Available: {$d['assets']['available']}, Assigned: {$d['assets']['assigned']}, Under Maintenance: {$d['assets']['under_maintenance']}, Lost: {$d['assets']['lost']}\n";
    echo "Maintenance — Total: {$d['maintenance']['total']}, Scheduled: {$d['maintenance']['scheduled']}, In Progress: {$d['maintenance']['in_progress']}, Completed: {$d['maintenance']['completed']}\n";
    echo "Audit — Total: {$d['audit']['total']}, Completed: {$d['audit']['completed']}, Pending: {$d['audit']['pending']}\n";

}

exit;