<?php

require_once "../../auth/check_auth.php";
require_once __DIR__ . "/../../includes/report_functions.php";

$type = trim($_GET['report_type'] ?? '');
$generatedBy = trim($_GET['generated_by'] ?? '');
$reportPeriod = trim($_GET['report_period'] ?? 'Monthly');
$dateRange = normalizeReportDateRange(
    $_GET['start_date'] ?? null,
    $_GET['end_date'] ?? null
);

if (!isAllowedReportType($type)) {
    header("Location: index.php");
    exit;
}

if ($generatedBy === '') {
    $generatedBy = 'On Demand';
}

if (
    !in_array($reportPeriod, getAllowedReportPeriods(), true) ||
    $dateRange === null
) {
    header("Location: index.php?error=invalid_date_range");
    exit;
}

$history = generateHistoricalActivityReport(
    $type,
    $dateRange['start_date'],
    $dateRange['end_date']
);
$periodLabel = formatReportPeriodLabel(
    $reportPeriod,
    $dateRange['start_date'],
    $dateRange['end_date']
);
$fileBase = preg_replace('/[^A-Za-z0-9_-]+/', '_', $type);
$fileName = $fileBase . '_' . $dateRange['start_date'] . '_to_' .
    $dateRange['end_date'] . '.txt';

header('Content-Type: text/plain; charset=UTF-8');
header('Content-Disposition: attachment; filename="' . $fileName . '"');

echo "Report Name: {$type} - {$periodLabel}\n";
echo "Report Type: {$type}\n";
echo "Report Period: {$reportPeriod}\n";
echo "Generated By: {$generatedBy}\n";
echo "Date Generated: " . getReportToday() . "\n";
echo "Activity Period: {$periodLabel} ({$dateRange['start_date']} to {$dateRange['end_date']})\n";
echo "Historical Events: {$history['total_events']}\n";
echo "Included Modules: " . implode(', ', getReportEventModules($type)) . "\n";
echo "Status: Generated\n";

echo str_repeat('-', 72) . "\n\n";
echo "PERIOD ACTIVITY\n";

foreach ($history['period_metrics'] as $label => $value) {
    $prefix = $value > 0 && str_contains($label, 'Change') ? '+' : '';
    echo "{$label}: {$prefix}{$value}\n";
}

if ($type === 'Full System Report') {
    echo "\nEvents by Module:\n";

    if (empty($history['module_totals'])) {
        echo "  No historical activity.\n";
    } else {
        foreach ($history['module_totals'] as $module => $count) {
            echo "  {$module}: {$count}\n";
        }
    }
}

echo "\nEvents by Type:\n";

if (empty($history['event_type_totals'])) {
    echo "  No historical activity.\n";
} else {
    foreach ($history['event_type_totals'] as $eventType => $count) {
        echo "  {$eventType}: {$count}\n";
    }
}

echo "\n" . str_repeat('=', 72) . "\n";
echo "ACTIVITY TIMELINE\n";

if (empty($history['events'])) {
    echo "No historical events were recorded for this report module and date range.\n";
} else {
    foreach ($history['events'] as $event) {
        $record = $event['business_id'];

        if (!empty($event['record_name_snap'])) {
            $record .= ' - ' . $event['record_name_snap'];
        }

        if (!empty($event['related_business_id'])) {
            $record .= ' (Related: ' . $event['related_business_id'] . ')';
        }

        $actor = !empty($event['performed_by'])
            ? $event['performed_by']
            : 'System';

        echo "[{$event['event_date']}] {$event['module']} / " .
            "{$event['event_type']} / {$record} / " .
            describePropertyEvent($event) . " / By: {$actor}\n";
    }
}

exit;
