<?php

require_once "../../auth/check_auth.php";

$id = $_GET['id'] ?? null;
$report = $_SESSION['reports'][$id] ?? null;

if ($report) {
    header('Content-Type: text/plain');
    header('Content-Disposition: attachment; filename="' . rawurlencode($report['report_name'] ?? 'report') . '.txt"');
    echo "Report ID: {$report['report_id']}\n";
    echo "Report Name: {$report['report_name']}\n";
    echo "Report Type: {$report['report_type']}\n";
    echo "Generated By: {$report['generated_by']}\n";
    echo "Date Generated: {$report['date_generated']}\n";
    echo "Status: {$report['status']}\n";
    exit;
}

header("Location: index.php");
exit;
