<?php

require_once "../../auth/check_auth.php";
require_once __DIR__ . "/../../includes/asset_functions.php";

if (!isset($_SESSION['reports'])) {
    $_SESSION['reports'] = [];
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {

    $_SESSION['reports'][] = [
        'report_id' => $_POST['report_id'] ?? generateReportID(),
        'report_name' => $_POST['report_name'],
        'report_type' => $_POST['report_type'],
        'generated_by' => $_POST['generated_by'],
        'date_generated' => $_POST['date_generated'],
        'status' => $_POST['status']
    ];

    header("Location: index.php");
    exit;
}

?>

<form class="asset-form" method="POST" action="generate_report.php">

    <input type="hidden" name="report_id" id="reportID">

    <h2>Generate New Report</h2>

    <div class="form-row">
        <label>Report Name</label>
        <input type="text" name="report_name" required>
    </div>

    <div class="form-row">
        <label>Report Type</label>
        <select name="report_type">
            <option>Asset Report</option>
            <option>Inventory Report</option>
            <option>Maintenance Report</option>
            <option>Procurement Report</option>
            <option>Audit Report</option>
        </select>
    </div>

    <div class="form-row">
        <label>Generated By</label>
        <input type="text" name="generated_by" required>
    </div>

    <div class="form-row">
        <label>Date Generated</label>
        <input type="date" name="date_generated" required>
    </div>

    <div class="form-row">
        <label>Status</label>
        <select name="status">
            <option>Generated</option>
            <option>Pending</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Save Report</button>

</form>
