<?php

require_once "../../auth/check_auth.php";
require_once __DIR__ . "/../../includes/report_functions.php";

if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    $reportType =
        trim($_POST['report_type'] ?? '');

    $generatedBy =
        trim($_POST['generated_by'] ?? '');

    $dateRange = resolveReportPeriod($_POST);

    if (!isAllowedReportType($reportType) || $generatedBy === '') {
        header("Location: index.php?error=invalid_report");
        exit;
    }

    if ($dateRange === null) {
        header("Location: index.php?error=invalid_date_range");
        exit;
    }

    $query = http_build_query([
        'report_type' => $reportType,
        'generated_by' => $generatedBy,
        'report_period' => $dateRange['report_period'],
        'start_date' => $dateRange['start_date'],
        'end_date' => $dateRange['end_date'],
    ]);

    header(
        "Location: view_report.php?" . $query
    );

    exit;
}

?>

<form
    class="asset-form"
    method="POST"
    action="generate_report.php"
>

<h2>Generate New Report</h2>

<div class="form-row">

<label>Report Type</label>

<select
    name="report_type"
    required
>

<?php foreach (getAllowedReportTypes() as $reportType): ?>

<option value="<?= htmlspecialchars($reportType) ?>">
    <?= htmlspecialchars($reportType) ?>
</option>

<?php endforeach; ?>

</select>

</div>

<?php $defaultDateRange = getDefaultReportDateRange(); ?>

<div class="form-row">

<label>Report Period</label>

<select name="report_period" required>

<?php foreach (getAllowedReportPeriods() as $period): ?>

<option value="<?= htmlspecialchars($period) ?>" <?= $period === 'Monthly' ? 'selected' : '' ?>>
    <?= htmlspecialchars($period) ?>
</option>

<?php endforeach; ?>

</select>

</div>

<div class="form-row">

<label>Date</label>

<input type="date" name="period_date" value="<?= htmlspecialchars(getReportToday()) ?>">

</div>

<div class="form-row">

<label>Week Of</label>

<input type="date" name="week_of" value="<?= htmlspecialchars(getReportToday()) ?>">

</div>

<div class="form-row">

<label>Month</label>

<select name="period_month">
<?php for ($month = 1; $month <= 12; $month++): ?>
<option value="<?= $month ?>" <?= $month === (int) getReportNow()->format('n') ? 'selected' : '' ?>>
<?= htmlspecialchars(DateTimeImmutable::createFromFormat('!n', (string) $month)->format('F')) ?>
</option>
<?php endfor; ?>
</select>

</div>

<div class="form-row">

<label>Quarter</label>

<select name="period_quarter">
<?php for ($quarter = 1; $quarter <= 4; $quarter++): ?>
<option value="<?= $quarter ?>">Q<?= $quarter ?></option>
<?php endfor; ?>
</select>

</div>

<div class="form-row">

<label>Year</label>

<input type="number" name="period_year" min="2000" max="2100" value="<?= htmlspecialchars(getReportNow()->format('Y')) ?>">

</div>

<div class="form-row">

<label>Activity Start Date</label>

<input
    type="date"
    name="start_date"
    value="<?= htmlspecialchars($defaultDateRange['start_date']) ?>"
    required
>

</div>

<div class="form-row">

<label>Activity End Date</label>

<input
    type="date"
    name="end_date"
    value="<?= htmlspecialchars($defaultDateRange['end_date']) ?>"
    required
>

</div>

<div class="form-row">

<label>Generated By</label>

<input
    type="text"
    name="generated_by"
    value="<?= htmlspecialchars($_SESSION['user']['name'] ?? '') ?>"
    required
>

</div>

<div class="form-row">

<label>Date Generated</label>

<input
    type="date"
    value="<?= htmlspecialchars(getReportToday()) ?>"
    readonly
>

</div>

<button
    type="submit"
    class="btn btn-primary"
>
Generate Report
</button>

</form>
