<?php

require_once "../../auth/check_auth.php";

if (!isset($_SESSION['reports'])) {
    $_SESSION['reports'] = [];
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {

    $reportType = $_POST['report_type'] ?? 'Asset Report';

    $_SESSION['reports'][] = [
        'report_id' => $_POST['report_id'] ?? ('RPT-' . str_pad(count($_SESSION['reports']) + 1, 6, '0', STR_PAD_LEFT)),
        'report_name' => $reportType . ' - ' . date('Y-m-d'),
        'report_type' => $reportType,
        'generated_by' => $_POST['generated_by'],
        'date_generated' => date('Y-m-d'),
        'status' => 'Generated'
    ];

    header("Location: index.php");
    exit;
}

?>

<form class="asset-form" method="POST" action="generate_report.php">

    <input type="hidden" name="report_id" id="reportID">

    <h2>Generate New Report</h2>

    <div class="form-row">
        <label>Report Type</label>
        <select name="report_type" required>
            <option>Asset Report</option>
            <option>Inventory Report</option>
            <option>Maintenance Report</option>
            <option>Procurement Report</option>
            <option>Audit Report</option>
            <option>Full System Report</option>
        </select>
    </div>

    <div class="form-row">
        <label>Generated By</label>
        <input type="text" name="generated_by" required>
    </div>

    <div class="form-row">
        <label>Date Generated</label>
        <input type="date" value="<?= date('Y-m-d') ?>" readonly>
    </div>

    <button type="submit" class="btn btn-primary">Generate Report</button>

</form>