<?php

require_once "../../auth/check_auth.php";
require_once __DIR__ . "/../../includes/report_functions.php";

include "../../includes/header.php";

?>

<div class="layout">

<?php include "../../includes/sidebar.php"; ?>

<div class="main-content">

<h1>Reports Management</h1>

<hr>

<br>

<?php if (($_GET['error'] ?? '') === 'invalid_report'): ?>

<div class="error-message">

Please select a valid Report Type and provide the Generated By field.

</div>

<br>

<?php endif; ?>

<div class="search-toolbar">

<form
    method="GET"
    action="search_reports.php"
    style="display:flex; gap:15px; flex-wrap:wrap; align-items:center;"
>

<input
    type="text"
    id="searchInput"
    name="search"
    placeholder="Search Reports..."
    value="<?= htmlspecialchars($_GET['search'] ?? '') ?>"
>

<select
    id="reportType"
    name="report_type"
>

<option value="">
All Report Types
</option>

<?php foreach (getAllowedReportTypes() as $reportType): ?>

<option
    value="<?= htmlspecialchars($reportType) ?>"
    <?= (($_GET['report_type'] ?? '') === $reportType) ? 'selected' : '' ?>
>
<?= htmlspecialchars($reportType) ?>
</option>

<?php endforeach; ?>

</select>

<button
    type="submit"
    class="btn btn-primary"
>
Search
</button>

</form>

<button
    type="button"
    id="openReportModal"
    class="btn btn-primary"
>
Generate Report
</button>

</div>

<br>

<?php include "reports_table.php"; ?>

<div
    id="reportModal"
    class="modal"
>

<div class="modal-content">

<span class="close-modal">&times;</span>

<?php include "generate_report.php"; ?>

</div>

</div>

</div>

</div>

<script src="<?= BASE_URL ?>assets/js/reports.js"></script>

<?php include "../../includes/footer.php"; ?>