<div id="reportModal" class="modal pcms-modal pcms-modal--md" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="generateReportTitle">
<div class="modal-content pcms-modal-dialog">
<form id="generateReportForm" class="pcms-modal-form" method="POST" action="generate_report.php">
<header class="pcms-modal-header"><div><span class="pcms-modal-eyebrow">Reports</span><h2 id="generateReportTitle">Generate New Report</h2><p>Build an on-demand operational summary from current system data.</p></div><button type="button" class="close-modal" data-modal-close aria-label="Close Generate Report"><span aria-hidden="true">&times;</span></button></header>
<div class="pcms-modal-body"><div class="pcms-form-grid">
    <div class="form-row pcms-form-span-2"><label for="generateReportType">Report Type</label><select id="generateReportType" name="report_type" required><?php foreach (getAllowedReportTypes() as $reportType): ?><option value="<?= htmlspecialchars($reportType) ?>"><?= htmlspecialchars($reportType) ?></option><?php endforeach; ?></select></div>
    <div class="form-row"><label for="reportGeneratedBy">Generated By</label><input type="text" id="reportGeneratedBy" name="generated_by" required></div>
    <div class="form-row"><label for="reportGeneratedDate">Date Generated</label><input type="date" id="reportGeneratedDate" value="<?= htmlspecialchars(date('Y-m-d')) ?>" readonly></div>
</div></div>
<footer class="pcms-modal-footer"><button type="button" class="btn btn-outline" data-modal-close>Cancel</button><button type="submit" class="btn btn-primary">Generate Report</button></footer>
</form></div></div>

<div id="viewReportModal" class="modal pcms-modal pcms-modal--xl" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="viewReportTitle">
<div class="modal-content pcms-modal-dialog">
<header class="pcms-modal-header"><div><span class="pcms-modal-eyebrow">Reports</span><h2 id="viewReportTitle">Report Preview</h2><p id="viewReportSubtitle">Loading current report data…</p></div><button type="button" class="close-modal" data-modal-close aria-label="Close Report Preview"><span aria-hidden="true">&times;</span></button></header>
<div class="pcms-modal-body pcms-report-content" id="reportPreviewBody"><div class="pcms-report-loading"><span class="pcms-loading-spinner" aria-hidden="true"></span><strong>Loading report…</strong></div></div>
<footer class="pcms-modal-footer"><button type="button" class="btn btn-outline" data-modal-close>Close</button><a id="reportPreviewDownload" href="download_report.php" class="btn btn-warning">Download</a></footer>
</div></div>
