<table class="asset-table">

    <thead>

        <tr>

            <th>Report ID</th>
            <th>Report Name</th>
            <th>Report Type</th>
            <th>Generated By</th>
            <th>Date Generated</th>
            <th>Status</th>
            <th>Actions</th>

        </tr>

    </thead>

    <tbody>

        <tr>

            <td colspan="7" style="text-align:center; padding:40px;">

                No reports found.

            </td>

        </tr>

    </tbody>

</table>