<div id="reportModal" class="modal pcms-modal pcms-modal--md" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="generateReportTitle">
<div class="modal-content pcms-modal-dialog">
<form id="generateReportForm" class="pcms-modal-form" method="POST" action="generate_report.php">
<header class="pcms-modal-header"><div><span class="pcms-modal-eyebrow">Reports</span><h2 id="generateReportTitle">Generate New Report</h2><p>Select a standard reporting period or define a custom date range.</p></div><button type="button" class="close-modal" data-modal-close aria-label="Close Generate Report"><span aria-hidden="true">&times;</span></button></header>
<div class="pcms-modal-body"><div class="pcms-form-grid">
    <div class="form-row pcms-form-span-2"><label for="generateReportType">Report Type</label><select id="generateReportType" name="report_type" required><?php foreach (getAllowedReportTypes() as $reportType): ?><option value="<?= htmlspecialchars($reportType) ?>"><?= htmlspecialchars($reportType) ?></option><?php endforeach; ?></select></div>
    <?php $defaultReportRange = getDefaultReportDateRange(); ?>
    <?php $reportNow = getReportNow(); ?>
    <div class="form-row pcms-form-span-2"><label for="reportPeriod">Report Period</label><select id="reportPeriod" name="report_period" required><?php foreach (getAllowedReportPeriods() as $period): ?><option value="<?= htmlspecialchars($period) ?>" <?= $period === 'Monthly' ? 'selected' : '' ?>><?= htmlspecialchars($period) ?></option><?php endforeach; ?></select></div>
    <div class="form-row pcms-form-span-2" data-report-period-field="Daily" hidden><label for="reportPeriodDate">Date</label><input type="date" id="reportPeriodDate" name="period_date" value="<?= htmlspecialchars(getReportToday()) ?>"></div>
    <div class="form-row pcms-form-span-2" data-report-period-field="Weekly" hidden><label for="reportWeekOf">Week Of</label><input type="date" id="reportWeekOf" name="week_of" value="<?= htmlspecialchars(getReportToday()) ?>"><small>The report covers Monday through Sunday.</small></div>
    <div class="form-row" data-report-period-field="Monthly"><label for="reportPeriodMonth">Month</label><select id="reportPeriodMonth" name="period_month"><?php for ($month = 1; $month <= 12; $month++): ?><option value="<?= $month ?>" <?= $month === (int) $reportNow->format('n') ? 'selected' : '' ?>><?= htmlspecialchars(DateTimeImmutable::createFromFormat('!n', (string) $month)->format('F')) ?></option><?php endfor; ?></select></div>
    <div class="form-row" data-report-period-field="Quarterly" hidden><label for="reportPeriodQuarter">Quarter</label><select id="reportPeriodQuarter" name="period_quarter"><?php for ($quarter = 1; $quarter <= 4; $quarter++): ?><option value="<?= $quarter ?>" <?= $quarter === (int) ceil((int) $reportNow->format('n') / 3) ? 'selected' : '' ?>>Q<?= $quarter ?></option><?php endfor; ?></select></div>
    <div class="form-row" data-report-period-field="Monthly Quarterly Annual"><label for="reportPeriodYear">Year</label><input type="number" id="reportPeriodYear" name="period_year" min="2000" max="2100" value="<?= htmlspecialchars($reportNow->format('Y')) ?>"></div>
    <div class="form-row" data-report-period-field="Custom Date Range" hidden><label for="reportStartDate">Start Date</label><input type="date" id="reportStartDate" name="start_date" value="<?= htmlspecialchars($defaultReportRange['start_date']) ?>"></div>
    <div class="form-row" data-report-period-field="Custom Date Range" hidden><label for="reportEndDate">End Date</label><input type="date" id="reportEndDate" name="end_date" value="<?= htmlspecialchars($defaultReportRange['end_date']) ?>"></div>
    <div class="form-row"><label for="reportGeneratedBy">Generated By</label><input type="text" id="reportGeneratedBy" name="generated_by" value="<?= htmlspecialchars($_SESSION['user']['name'] ?? '') ?>" required></div>
    <div class="form-row"><label for="reportGeneratedDate">Date Generated</label><input type="date" id="reportGeneratedDate" value="<?= htmlspecialchars(getReportToday()) ?>" readonly></div>
</div></div>
<footer class="pcms-modal-footer"><button type="button" class="btn btn-outline" data-modal-close>Cancel</button><button type="submit" class="btn btn-primary">Generate Report</button></footer>
</form></div></div>

<div id="viewReportModal" class="modal pcms-modal pcms-modal--xl" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="viewReportTitle">
<div class="modal-content pcms-modal-dialog">
<header class="pcms-modal-header"><div><span class="pcms-modal-eyebrow">Reports</span><h2 id="viewReportTitle">Report Preview</h2><p id="viewReportSubtitle">Loading current report data…</p></div><button type="button" class="close-modal" data-modal-close aria-label="Close Report Preview"><span aria-hidden="true">&times;</span></button></header>
<div class="pcms-modal-body pcms-report-content" id="reportPreviewBody"><div class="pcms-report-loading"><span class="pcms-loading-spinner" aria-hidden="true"></span><strong>Loading report…</strong></div></div>
<footer class="pcms-modal-footer"><button type="button" class="btn btn-outline" data-modal-close>Close</button><button type="button" class="btn btn-primary" id="reportPreviewPrint">Print</button><a id="reportPreviewDownload" href="download_report.php" class="btn btn-warning">Download</a></footer>
</div></div>
