<?php

require_once "../../auth/check_auth.php";
require_once __DIR__ . "/../../includes/report_functions.php";

$type =
    trim($_GET['report_type'] ?? '');

$generatedBy =
    trim($_GET['generated_by'] ?? '');

$reportPeriod =
    trim($_GET['report_period'] ?? 'Monthly');

$dateRange = normalizeReportDateRange(
    $_GET['start_date'] ?? null,
    $_GET['end_date'] ?? null
);

if (!isAllowedReportType($type)) {
    header("Location: index.php");
    exit;
}

if ($generatedBy === '') {
    $generatedBy = 'On Demand';
}

if (!in_array($reportPeriod, getAllowedReportPeriods(), true)) {
    header("Location: index.php?error=invalid_date_range");
    exit;
}

if ($dateRange === null) {
    header("Location: index.php?error=invalid_date_range");
    exit;
}

$history = generateHistoricalActivityReport(
    $type,
    $dateRange['start_date'],
    $dateRange['end_date']
);

$periodLabel = formatReportPeriodLabel(
    $reportPeriod,
    $dateRange['start_date'],
    $dateRange['end_date']
);

$report = [
    'report_name' =>
        $type . ' - ' .
        $periodLabel,

    'report_type' =>
        $type,

    'generated_by' =>
        $generatedBy,

    'date_generated' =>
        getReportToday(),

    'status' =>
        'Generated'
];

include "../../includes/header.php";

?>

<div class="layout">

<?php include "../../includes/sidebar.php"; ?>

<div class="main-content">

<h1>View Report</h1>

<hr>
<br>

<table class="asset-table">

<tr>
<th style="width:220px;">Report Name</th>
<td><?= htmlspecialchars($report['report_name']) ?></td>
</tr>

<tr>
<th>Report Type</th>
<td><?= htmlspecialchars($report['report_type']) ?></td>
</tr>

<tr>
<th>Generated By</th>
<td><?= htmlspecialchars($report['generated_by']) ?></td>
</tr>

<tr>
<th>Date Generated</th>
<td><?= htmlspecialchars($report['date_generated']) ?></td>
</tr>

<tr>
<th>Report Period</th>
<td><?= htmlspecialchars($reportPeriod) ?></td>
</tr>

<tr>
<th>Activity Period</th>
<td><?= htmlspecialchars($periodLabel) ?> (<?= htmlspecialchars($dateRange['start_date']) ?> to <?= htmlspecialchars($dateRange['end_date']) ?>)</td>
</tr>

<tr>
<th>Historical Events</th>
<td><?= (int) $history['total_events'] ?></td>
</tr>

<tr>
<th>Status</th>
<td><?= htmlspecialchars($report['status']) ?></td>
</tr>

</table>

<br>

<h2>Period Activity</h2>

<p>
<strong><?= htmlspecialchars($periodLabel) ?></strong>
— figures below are derived only from events inside the selected period.
</p>

<table class="asset-table">

<?php foreach ($history['period_metrics'] as $label => $value): ?>

<tr>
<th><?= htmlspecialchars($label) ?></th>
<td><?= (int) $value > 0 && str_contains($label, 'Change') ? '+' : '' ?><?= (int) $value ?></td>
</tr>

<?php endforeach; ?>

</table>

<br>

<h2>Current System Snapshot</h2>

<?php if ($type === 'Procurement Report'): ?>

<?php $data = generateProcurementSummary(); ?>

<h3>Procurement Summary</h3>

<table class="asset-table">

<tr><th>Total Requests</th><td><?= $data['total'] ?></td></tr>
<tr><th>Pending</th><td><?= $data['pending'] ?></td></tr>
<tr><th>Approved</th><td><?= $data['approved'] ?></td></tr>
<tr><th>Delivered</th><td><?= $data['delivered'] ?></td></tr>
<tr><th>Rejected</th><td><?= $data['rejected'] ?></td></tr>

</table>

<br>

<h3>Requests by Supplier</h3>

<table class="asset-table">

<?php foreach ($data['by_supplier'] as $supplier => $count): ?>

<tr>
<th><?= htmlspecialchars($supplier) ?></th>
<td><?= (int) $count ?></td>
</tr>

<?php endforeach; ?>

<?php if (empty($data['by_supplier'])): ?>

<tr>
<td colspan="2">No data available.</td>
</tr>

<?php endif; ?>

</table>

<br>

<h3>Recent Procurement Activity</h3>

<table class="asset-table">

<tr>
<th>Procurement ID</th>
<th>Item</th>
<th>Status</th>
</tr>

<?php foreach ($data['recent'] as $item): ?>

<tr>

<td><?= htmlspecialchars($item['procurement_id']) ?></td>
<td><?= htmlspecialchars($item['item_name']) ?></td>
<td><?= htmlspecialchars($item['status']) ?></td>

</tr>

<?php endforeach; ?>

<?php if (empty($data['recent'])): ?>

<tr>
<td colspan="3">No records found.</td>
</tr>

<?php endif; ?>

</table>

<?php elseif ($type === 'Inventory Report'): ?>

<?php $data = generateInventorySummary(); ?>

<h3>Inventory Summary</h3>

<table class="asset-table">

<tr><th>Total Inventory Items</th><td><?= $data['total_items'] ?></td></tr>
<tr><th>Current Total Stock</th><td><?= $data['total_stock'] ?></td></tr>
<tr><th>Low Stock Items</th><td><?= $data['low_stock'] ?></td></tr>
<tr><th>Out of Stock Items</th><td><?= $data['out_of_stock'] ?></td></tr>
<tr><th>Ready for Registration</th><td><?= $data['ready_for_registration'] ?></td></tr>

</table>

<br>

<h3>Recently Delivered (from Procurement)</h3>

<table class="asset-table">

<tr>
<th>Procurement ID</th>
<th>Item</th>
<th>Quantity</th>
</tr>

<?php foreach ($data['recently_delivered'] as $item): ?>

<tr>

<td><?= htmlspecialchars($item['procurement_id']) ?></td>
<td><?= htmlspecialchars($item['item_name']) ?></td>
<td><?= (int) $item['quantity'] ?></td>

</tr>

<?php endforeach; ?>

<?php if (empty($data['recently_delivered'])): ?>

<tr>
<td colspan="3">No records found.</td>
</tr>

<?php endif; ?>

</table>

<?php elseif ($type === 'Asset Report'): ?>

<?php $data = generateAssetSummary(); ?>

<h3>Asset Registry Summary</h3>

<table class="asset-table">

<tr><th>Total Registered Assets</th><td><?= $data['total'] ?></td></tr>
<tr><th>Available</th><td><?= $data['available'] ?></td></tr>
<tr><th>Assigned</th><td><?= $data['assigned'] ?></td></tr>
<tr><th>Under Maintenance</th><td><?= $data['under_maintenance'] ?></td></tr>
<tr><th>Lost</th><td><?= $data['lost'] ?></td></tr>

</table>

<br>

<h3>Assets by Category</h3>

<table class="asset-table">

<?php foreach ($data['by_category'] as $category => $count): ?>

<tr>
<th><?= htmlspecialchars($category) ?></th>
<td><?= (int) $count ?></td>
</tr>

<?php endforeach; ?>

<?php if (empty($data['by_category'])): ?>

<tr>
<td colspan="2">No records found.</td>
</tr>

<?php endif; ?>

</table>

<br>

<h3>Assets by Location</h3>

<table class="asset-table">

<?php foreach ($data['by_location'] as $location => $count): ?>

<tr>
<th><?= htmlspecialchars($location) ?></th>
<td><?= (int) $count ?></td>
</tr>

<?php endforeach; ?>

<?php if (empty($data['by_location'])): ?>

<tr>
<td colspan="2">No records found.</td>
</tr>

<?php endif; ?>

</table>

<br>

<h3>Assets by Custodian</h3>

<table class="asset-table">

<?php foreach ($data['by_custodian'] as $custodian => $count): ?>

<tr>
<th><?= htmlspecialchars($custodian) ?></th>
<td><?= (int) $count ?></td>
</tr>

<?php endforeach; ?>

<?php if (empty($data['by_custodian'])): ?>

<tr>
<td colspan="2">No assigned custodians.</td>
</tr>

<?php endif; ?>

</table>

<?php elseif ($type === 'Maintenance Report'): ?>

<?php $data = generateMaintenanceSummary(); ?>

<h3>Maintenance Summary</h3>

<table class="asset-table">

<tr><th>Total Maintenance Records</th><td><?= $data['total'] ?></td></tr>
<tr><th>Scheduled</th><td><?= $data['scheduled'] ?></td></tr>
<tr><th>In Progress</th><td><?= $data['in_progress'] ?></td></tr>
<tr><th>Completed</th><td><?= $data['completed'] ?></td></tr>
<tr><th>Currently Active Maintenance</th><td><?= $data['currently_under_maintenance'] ?></td></tr>

</table>

<br>

<h3>Maintenance History (Recent)</h3>

<table class="asset-table">

<tr>
<th>Maintenance ID</th>
<th>Asset</th>
<th>Status</th>
</tr>

<?php foreach ($data['recent'] as $item): ?>

<tr>

<td><?= htmlspecialchars($item['maintenance_id']) ?></td>
<td><?= htmlspecialchars($item['asset_name']) ?></td>
<td><?= htmlspecialchars($item['status']) ?></td>

</tr>

<?php endforeach; ?>

<?php if (empty($data['recent'])): ?>

<tr>
<td colspan="3">No records found.</td>
</tr>

<?php endif; ?>

</table>

<?php elseif ($type === 'Audit Report'): ?>

<?php $data = generateAuditSummary(); ?>

<h3>Audit Summary</h3>

<table class="asset-table">

<tr><th>Total Audit Records</th><td><?= $data['total'] ?></td></tr>
<tr><th>Completed Audits</th><td><?= $data['completed'] ?></td></tr>
<tr><th>Pending Audits</th><td><?= $data['pending'] ?></td></tr>

</table>

<br>

<h3>Recent Audit Activity</h3>

<table class="asset-table">

<tr>
<th>Audit ID</th>
<th>Asset</th>
<th>Result</th>
</tr>

<?php foreach ($data['recent'] as $item): ?>

<tr>

<td><?= htmlspecialchars($item['audit_id']) ?></td>
<td><?= htmlspecialchars($item['asset_name']) ?></td>
<td><?= htmlspecialchars($item['result']) ?></td>

</tr>

<?php endforeach; ?>

<?php if (empty($data['recent'])): ?>

<tr>
<td colspan="3">No records found.</td>
</tr>

<?php endif; ?>

</table>

<?php elseif ($type === 'Full System Report'): ?>

<?php $data = generateFullSystemSummary(); ?>

<h3>Full System Summary</h3>

<table class="asset-table">

<tr>
<th>Procurement — Total</th>
<td>
<?= $data['procurement']['total'] ?>
(Pending: <?= $data['procurement']['pending'] ?>,
Approved: <?= $data['procurement']['approved'] ?>,
Delivered: <?= $data['procurement']['delivered'] ?>,
Rejected: <?= $data['procurement']['rejected'] ?>)
</td>
</tr>

<tr>
<th>Inventory — Items</th>
<td>
<?= $data['inventory']['total_items'] ?>
(Stock: <?= $data['inventory']['total_stock'] ?>,
Low Stock: <?= $data['inventory']['low_stock'] ?>,
Out of Stock: <?= $data['inventory']['out_of_stock'] ?>)
</td>
</tr>

<tr>
<th>Assets — Total</th>
<td>
<?= $data['assets']['total'] ?>
(Available: <?= $data['assets']['available'] ?>,
Assigned: <?= $data['assets']['assigned'] ?>,
Under Maintenance: <?= $data['assets']['under_maintenance'] ?>,
Lost: <?= $data['assets']['lost'] ?>)
</td>
</tr>

<tr>
<th>Maintenance — Total</th>
<td>
<?= $data['maintenance']['total'] ?>
(Scheduled: <?= $data['maintenance']['scheduled'] ?>,
In Progress: <?= $data['maintenance']['in_progress'] ?>,
Completed: <?= $data['maintenance']['completed'] ?>)
</td>
</tr>

<tr>
<th>Audit — Total</th>
<td>
<?= $data['audit']['total'] ?>
(Completed: <?= $data['audit']['completed'] ?>,
Pending: <?= $data['audit']['pending'] ?>)
</td>
</tr>

</table>

<?php endif; ?>

<br>

<h3>Historical Activity</h3>

<p>
Events dated
<strong><?= htmlspecialchars($history['start_date']) ?></strong>
through
<strong><?= htmlspecialchars($history['end_date']) ?></strong>.
</p>

<table class="asset-table">

<tr>
<th>Total Events</th>
<td><?= (int) $history['total_events'] ?></td>
</tr>

<tr>
<th>Net Inventory Stock Change</th>
<td><?= $history['net_inventory_stock_change'] > 0 ? '+' : '' ?><?= (int) $history['net_inventory_stock_change'] ?></td>
</tr>

</table>

<?php if ($type === 'Full System Report'): ?>

<br>

<h3>Events by Module</h3>

<table class="asset-table">

<?php foreach ($history['module_totals'] as $module => $count): ?>

<tr>
<th><?= htmlspecialchars($module) ?></th>
<td><?= (int) $count ?></td>
</tr>

<?php endforeach; ?>

<?php if (empty($history['module_totals'])): ?>

<tr><td colspan="2">No historical activity in this period.</td></tr>

<?php endif; ?>

</table>

<?php endif; ?>

<br>

<h3>Events by Type</h3>

<table class="asset-table">

<?php foreach ($history['event_type_totals'] as $eventType => $count): ?>

<tr>
<th><?= htmlspecialchars($eventType) ?></th>
<td><?= (int) $count ?></td>
</tr>

<?php endforeach; ?>

<?php if (empty($history['event_type_totals'])): ?>

<tr><td colspan="2">No historical activity in this period.</td></tr>

<?php endif; ?>

</table>

<br>

<h3>Activity Timeline</h3>

<div class="pcms-table-scroll">

<table class="asset-table">

<thead>
<tr>
<th>Date</th>
<th>Module</th>
<th>Event</th>
<th>Record</th>
<th>Change / Outcome</th>
<th>Performed By</th>
</tr>
</thead>

<tbody>

<?php foreach ($history['events'] as $event): ?>

<tr>
<td><?= htmlspecialchars($event['event_date']) ?></td>
<td><?= htmlspecialchars($event['module']) ?></td>
<td><?= htmlspecialchars($event['event_type']) ?></td>
<td>
    <strong><?= htmlspecialchars($event['business_id']) ?></strong>
    <?php if (!empty($event['record_name_snap'])): ?>
    <br><?= htmlspecialchars($event['record_name_snap']) ?>
    <?php endif; ?>
    <?php if (!empty($event['related_business_id'])): ?>
    <br><small>Related: <?= htmlspecialchars($event['related_business_id']) ?></small>
    <?php endif; ?>
</td>
<td><?= htmlspecialchars(describePropertyEvent($event)) ?></td>
<td><?= !empty($event['performed_by']) ? htmlspecialchars($event['performed_by']) : 'System' ?></td>
</tr>

<?php endforeach; ?>

<?php if (empty($history['events'])): ?>

<tr><td colspan="6">No historical events were recorded in this date range.</td></tr>

<?php endif; ?>

</tbody>

</table>

</div>

<br>

<?php

$downloadQuery = http_build_query([
    'report_type' => $type,
    'generated_by' => $generatedBy,
    'report_period' => $reportPeriod,
    'start_date' => $dateRange['start_date'],
    'end_date' => $dateRange['end_date'],
]);

?>

<a
    href="index.php"
    class="btn btn-primary"
>
Back to Reports
</a>

<a
    href="download_report.php?<?= htmlspecialchars($downloadQuery) ?>"
    class="btn btn-warning"
>
Download
</a>

<button
    type="button"
    class="btn btn-primary pcms-print-trigger"
    onclick="window.print()"
>
Print
</button>

</div>

</div>

<?php include "../../includes/footer.php"; ?>
