<?php

require_once "../../auth/check_auth.php";
include "../../includes/header.php";

$id = $_GET['id'] ?? null;
$report = $_SESSION['reports'][$id] ?? null;

?>

<div class="layout">

    <?php include "../../includes/sidebar.php"; ?>

    <div class="main-content">

        <h1>View Report</h1>

        <hr>

        <?php if ($report): ?>

        <table class="asset-table">

            <tr><th style="width:220px;">Report ID</th><td><?= htmlspecialchars($report['report_id']) ?></td></tr>
            <tr><th>Report Name</th><td><?= htmlspecialchars($report['report_name']) ?></td></tr>
            <tr><th>Report Type</th><td><?= htmlspecialchars($report['report_type']) ?></td></tr>
            <tr><th>Generated By</th><td><?= htmlspecialchars($report['generated_by']) ?></td></tr>
            <tr><th>Date Generated</th><td><?= htmlspecialchars($report['date_generated']) ?></td></tr>
            <tr><th>Status</th><td><?= htmlspecialchars($report['status']) ?></td></tr>

        </table>

        <br>

        <a href="index.php" class="btn btn-primary">Back to Reports</a>

        <?php else: ?>

        <p>Report not found.</p>
        <a href="index.php" class="btn btn-primary">Back</a>

        <?php endif; ?>

    </div>

</div>

<?php include "../../includes/footer.php"; ?>
