<?php

require_once "../../auth/check_auth.php";
require_once __DIR__ . "/../../includes/report_functions.php";

$type = trim($_GET['report_type'] ?? '');
$generatedBy = trim($_GET['generated_by'] ?? '');
$reportPeriod = trim($_GET['report_period'] ?? 'Monthly');
$dateRange = normalizeReportDateRange(
    $_GET['start_date'] ?? null,
    $_GET['end_date'] ?? null
);

if (!isAllowedReportType($type)) {
    header("Location: index.php");
    exit;
}

if ($generatedBy === '') {
    $generatedBy = 'On Demand';
}

if (
    !in_array($reportPeriod, getAllowedReportPeriods(), true) ||
    $dateRange === null
) {
    header("Location: index.php?error=invalid_date_range");
    exit;
}

$history = generateHistoricalActivityReport(
    $type,
    $dateRange['start_date'],
    $dateRange['end_date']
);
$periodLabel = formatReportPeriodLabel(
    $reportPeriod,
    $dateRange['start_date'],
    $dateRange['end_date']
);
$downloadQuery = http_build_query([
    'report_type' => $type,
    'generated_by' => $generatedBy,
    'report_period' => $reportPeriod,
    'start_date' => $dateRange['start_date'],
    'end_date' => $dateRange['end_date'],
]);

include "../../includes/header.php";

?>

<div class="layout">
<?php include "../../includes/sidebar.php"; ?>

<div class="main-content">
<h1>Historical Activity Report</h1>
<hr>
<br>

<table class="asset-table">
<tr><th style="width:220px;">Report Name</th><td><?= htmlspecialchars($type . ' - ' . $periodLabel) ?></td></tr>
<tr><th>Report Type</th><td><?= htmlspecialchars($type) ?></td></tr>
<tr><th>Generated By</th><td><?= htmlspecialchars($generatedBy) ?></td></tr>
<tr><th>Date Generated</th><td><?= htmlspecialchars(getReportToday()) ?></td></tr>
<tr><th>Report Period</th><td><?= htmlspecialchars($reportPeriod) ?></td></tr>
<tr><th>Activity Period</th><td><?= htmlspecialchars($periodLabel) ?> (<?= htmlspecialchars($dateRange['start_date']) ?> to <?= htmlspecialchars($dateRange['end_date']) ?>)</td></tr>
<tr><th>Historical Events</th><td><?= (int) $history['total_events'] ?></td></tr>
<tr><th>Status</th><td>Generated</td></tr>
</table>

<br>
<h2>Period Activity</h2>
<p>
<strong><?= htmlspecialchars($periodLabel) ?></strong>
— every figure and timeline row below comes only from
<?= htmlspecialchars(implode(', ', getReportEventModules($type))) ?> events dated inside the selected period.
</p>

<table class="asset-table">
<?php foreach ($history['period_metrics'] as $label => $value): ?>
<tr>
<th><?= htmlspecialchars($label) ?></th>
<td><?= (int) $value > 0 && str_contains($label, 'Change') ? '+' : '' ?><?= (int) $value ?></td>
</tr>
<?php endforeach; ?>
</table>

<?php if ($type === 'Full System Report'): ?>
<br>
<h3>Events by Module</h3>
<table class="asset-table">
<?php foreach ($history['module_totals'] as $module => $count): ?>
<tr><th><?= htmlspecialchars($module) ?></th><td><?= (int) $count ?></td></tr>
<?php endforeach; ?>
<?php if (empty($history['module_totals'])): ?>
<tr><td colspan="2">No historical activity in this period.</td></tr>
<?php endif; ?>
</table>
<?php endif; ?>

<br>
<h3>Events by Type</h3>
<table class="asset-table">
<?php foreach ($history['event_type_totals'] as $eventType => $count): ?>
<tr><th><?= htmlspecialchars($eventType) ?></th><td><?= (int) $count ?></td></tr>
<?php endforeach; ?>
<?php if (empty($history['event_type_totals'])): ?>
<tr><td colspan="2">No historical activity in this period.</td></tr>
<?php endif; ?>
</table>

<br>
<h3>Activity Timeline</h3>
<div class="pcms-table-scroll">
<table class="asset-table">
<thead>
<tr>
<th>Date</th>
<th>Module</th>
<th>Event</th>
<th>Record</th>
<th>Change / Outcome</th>
<th>Performed By</th>
</tr>
</thead>
<tbody>
<?php foreach ($history['events'] as $event): ?>
<tr>
<td><?= htmlspecialchars($event['event_date']) ?></td>
<td><?= htmlspecialchars($event['module']) ?></td>
<td><?= htmlspecialchars($event['event_type']) ?></td>
<td>
<strong><?= htmlspecialchars($event['business_id']) ?></strong>
<?php if (!empty($event['record_name_snap'])): ?>
<br><?= htmlspecialchars($event['record_name_snap']) ?>
<?php endif; ?>
<?php if (!empty($event['related_business_id'])): ?>
<br><small>Related: <?= htmlspecialchars($event['related_business_id']) ?></small>
<?php endif; ?>
</td>
<td><?= htmlspecialchars(describePropertyEvent($event)) ?></td>
<td><?= !empty($event['performed_by']) ? htmlspecialchars($event['performed_by']) : 'System' ?></td>
</tr>
<?php endforeach; ?>
<?php if (empty($history['events'])): ?>
<tr><td colspan="6">No historical events were recorded for this report module and date range.</td></tr>
<?php endif; ?>
</tbody>
</table>
</div>

<br>
<a href="index.php" class="btn btn-primary">Back to Reports</a>
<a href="download_report.php?<?= htmlspecialchars($downloadQuery) ?>" class="btn btn-warning">Download</a>
<button type="button" class="btn btn-primary pcms-print-trigger" onclick="window.print()">Print</button>
</div>
</div>

<?php include "../../includes/footer.php"; ?>
